Get-Content ".\ElePh1.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX1.xml 
Get-Content ".\ElePh2.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX2.xml 
Get-Content ".\ElePh3.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX3.xml 
Get-Content ".\ElePh4.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX4.xml 
Get-Content ".\ElePh5.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX5.xml 
Get-Content ".\ElePh6.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX6.xml 
Get-Content ".\ElePh7.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX7.xml 
Get-Content ".\ElePh8.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX8.xml 
Get-Content ".\ElePh9.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX9.xml 
Get-Content ".\ElePh10.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX10.xml 
Get-Content ".\ElePh11.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX11.xml 
Get-Content ".\ElePh12.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX12.xml 
Get-Content ".\ElePh13.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX13.xml 
Get-Content ".\ElePh14.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX14.xml 
Get-Content ".\ElePh15.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX15.xml 
Get-Content ".\ElePh16.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX16.xml 
Get-Content ".\ElePh17.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX17.xml 
Get-Content ".\ElePh18.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX18.xml 
Get-Content ".\ElePh19.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX19.xml 
Get-Content ".\ElePh20.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX20.xml 
Get-Content ".\ElePh21.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX21.xml 
Get-Content ".\ElePh22.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX22.xml 
Get-Content ".\ElePh23.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX23.xml 
Get-Content ".\ElePh24.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX24.xml 
Get-Content ".\ElePh25.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX25.xml 
Get-Content ".\ElePh26.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX26.xml 
Get-Content ".\ElePh27.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX27.xml 
Get-Content ".\ElePh28.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX28.xml 
Get-Content ".\ElePh29.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX29.xml 
Get-Content ".\ElePh30.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX30.xml 
Get-Content ".\ElePh31.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX31.xml 
Get-Content ".\ElePh32.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX32.xml 
Get-Content ".\ElePh33.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX33.xml 
Get-Content ".\ElePh34.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX34.xml 
Get-Content ".\ElePh35.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX35.xml 
Get-Content ".\ElePh36.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX36.xml 
Get-Content ".\ElePh37.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX37.xml 
Get-Content ".\ElePh38.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX38.xml 
Get-Content ".\ElePh39.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX39.xml 
Get-Content ".\ElePh40.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX40.xml 
Get-Content ".\ElePh41.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX41.xml 
Get-Content ".\ElePh42.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX42.xml 
Get-Content ".\ElePh43.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX43.xml 
Get-Content ".\ElePh44.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX44.xml 
Get-Content ".\ElePh45.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX45.xml 
Get-Content ".\ElePh46.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX46.xml 
Get-Content ".\ElePh47.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX47.xml 
Get-Content ".\ElePh48.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX48.xml 
Get-Content ".\ElePh49.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX49.xml 
Get-Content ".\ElePh50.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX50.xml 
Get-Content ".\ElePh51.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX51.xml 
Get-Content ".\ElePh52.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX52.xml 
Get-Content ".\ElePh53.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX53.xml 
Get-Content ".\ElePh54.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX54.xml 
Get-Content ".\ElePh55.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX55.xml 
Get-Content ".\ElePh56.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX56.xml 
Get-Content ".\ElePh57.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX57.xml 
Get-Content ".\ElePh58.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX58.xml 
Get-Content ".\ElePh59.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX59.xml 
Get-Content ".\ElePh60.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX60.xml 
Get-Content ".\ElePh61.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX61.xml 
Get-Content ".\ElePh62.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX62.xml 
Get-Content ".\ElePh63.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX63.xml 
Get-Content ".\ElePh64.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX64.xml 
Get-Content ".\ElePh65.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX65.xml 
Get-Content ".\ElePh66.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX66.xml 
Get-Content ".\ElePh67.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX67.xml 
Get-Content ".\ElePh68.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX68.xml 
Get-Content ".\ElePh69.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX69.xml 
Get-Content ".\ElePh70.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX70.xml 
Get-Content ".\ElePh71.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX71.xml 
Get-Content ".\ElePh72.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX72.xml 
Get-Content ".\ElePh73.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX73.xml 
Get-Content ".\ElePh74.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX74.xml 
Get-Content ".\ElePh75.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX75.xml 
Get-Content ".\ElePh76.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX76.xml 
Get-Content ".\ElePh77.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX77.xml 
Get-Content ".\ElePh78.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX78.xml 
Get-Content ".\ElePh79.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX79.xml 
Get-Content ".\ElePh80.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX80.xml 
Get-Content ".\ElePh81.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX81.xml 
Get-Content ".\ElePh82.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX82.xml 
Get-Content ".\ElePh83.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX83.xml 
Get-Content ".\ElePh84.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX84.xml 
Get-Content ".\ElePh85.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX85.xml 
Get-Content ".\ElePh86.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX86.xml 
Get-Content ".\ElePh87.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX87.xml 
Get-Content ".\ElePh88.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX88.xml 
Get-Content ".\ElePh89.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX89.xml 
Get-Content ".\ElePh90.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX90.xml 
Get-Content ".\ElePh91.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX91.xml 
Get-Content ".\ElePh92.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX92.xml 
Get-Content ".\ElePh93.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX93.xml 
Get-Content ".\ElePh94.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX94.xml 
Get-Content ".\ElePh95.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX95.xml 
Get-Content ".\ElePh96.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX96.xml 
Get-Content ".\ElePh97.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX97.xml 
Get-Content ".\ElePh98.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX98.xml 
Get-Content ".\ElePh99.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX99.xml 
Get-Content ".\ElePh100.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX100.xml 
Get-Content ".\ElePh101.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX101.xml 
Get-Content ".\ElePh102.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX102.xml 
Get-Content ".\ElePh103.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX103.xml 
Get-Content ".\ElePh104.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX104.xml 
Get-Content ".\ElePh105.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX105.xml 
Get-Content ".\ElePh106.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX106.xml 
Get-Content ".\ElePh107.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX107.xml 
Get-Content ".\ElePh108.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX108.xml 
Get-Content ".\ElePh109.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX109.xml 
Get-Content ".\ElePh110.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX110.xml 
Get-Content ".\ElePh111.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX111.xml 
Get-Content ".\ElePh112.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX112.xml 
Get-Content ".\ElePh113.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX113.xml 
Get-Content ".\ElePh114.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX114.xml 
Get-Content ".\ElePh115.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX115.xml 
Get-Content ".\ElePh116.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX116.xml 
Get-Content ".\ElePh117.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX117.xml 
Get-Content ".\ElePh118.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX118.xml 
Get-Content ".\ElePh119.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX119.xml 
Get-Content ".\ElePh120.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX120.xml 
Get-Content ".\ElePh121.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX121.xml 
Get-Content ".\ElePh122.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX122.xml 
Get-Content ".\ElePh123.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX123.xml 
Get-Content ".\ElePh124.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX124.xml 
Get-Content ".\ElePh125.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX125.xml 
Get-Content ".\ElePh126.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX126.xml 
Get-Content ".\ElePh127.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX127.xml 
Get-Content ".\ElePh128.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX128.xml 
Get-Content ".\ElePh129.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX129.xml 
Get-Content ".\ElePh130.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX130.xml 
Get-Content ".\ElePh131.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX131.xml 
Get-Content ".\ElePh132.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX132.xml 
Get-Content ".\ElePh133.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX133.xml 
Get-Content ".\ElePh134.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX134.xml 
Get-Content ".\ElePh135.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX135.xml 
Get-Content ".\ElePh136.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX136.xml 
Get-Content ".\ElePh137.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX137.xml 
Get-Content ".\ElePh138.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX138.xml 
Get-Content ".\ElePh139.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX139.xml 
Get-Content ".\ElePh140.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX140.xml 
Get-Content ".\ElePh141.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX141.xml 
Get-Content ".\ElePh142.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX142.xml 
Get-Content ".\ElePh143.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX143.xml 
Get-Content ".\ElePh144.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX144.xml 
Get-Content ".\ElePh145.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX145.xml 
Get-Content ".\ElePh146.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX146.xml 
Get-Content ".\ElePh147.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX147.xml 
Get-Content ".\ElePh148.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX148.xml 
Get-Content ".\ElePh149.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX149.xml 
Get-Content ".\ElePh150.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX150.xml 
Get-Content ".\ElePh151.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX151.xml 
Get-Content ".\ElePh152.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX152.xml 
Get-Content ".\ElePh153.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX153.xml 
Get-Content ".\ElePh154.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX154.xml 
Get-Content ".\ElePh155.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX155.xml 
Get-Content ".\ElePh156.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX156.xml 
Get-Content ".\ElePh157.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX157.xml 
Get-Content ".\ElePh158.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX158.xml 
Get-Content ".\ElePh159.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX159.xml 
Get-Content ".\ElePh160.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX160.xml 
Get-Content ".\ElePh161.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX161.xml 
Get-Content ".\ElePh162.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX162.xml 
Get-Content ".\ElePh163.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX163.xml 
Get-Content ".\ElePh164.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX164.xml 
Get-Content ".\ElePh165.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX165.xml 
Get-Content ".\ElePh166.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX166.xml 
Get-Content ".\ElePh167.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX167.xml 
Get-Content ".\ElePh168.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX168.xml 
Get-Content ".\ElePh169.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX169.xml 
Get-Content ".\ElePh170.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX170.xml 
Get-Content ".\ElePh171.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX171.xml 
Get-Content ".\ElePh172.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX172.xml 
Get-Content ".\ElePh173.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX173.xml 
Get-Content ".\ElePh174.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX174.xml 
Get-Content ".\ElePh175.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX175.xml 
Get-Content ".\ElePh176.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX176.xml 
Get-Content ".\ElePh177.xml" | % { $_.Replace("Elephant ","") } | % { $_.Replace(" (", "") } | % { $_.Replace(")", "") } | Set-Content .\EleX177.xml 
